basic.showString("hi tim", 200)
basic.showString("ich habe", 200)
basic.showString("mich sehr", 200)
basic.showString("uber deine", 200)
basic.showString("Postkarte", 200)
basic.showString("gefreut", 200)
basic.showString("dein Philipp", 200)
